protected/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii,
    yii\filters\AccessControl,
    yii\web\Controller,
    app\models\LoginForm,
    app\models\User,
    app\models\TransferForm,
    app\models\Transfers;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Главная страница
     *
     * @return string
     */
    public function actionIndex()
    {
        $modelLogin = new LoginForm;
        $modelTransfer = new TransferForm;

        if (Yii::$app->request->isPost) {
            // POST авторизация
            if (Yii::$app->request->post('LoginForm') && $modelLogin->load(Yii::$app->request->post())) {
                $modelLogin->login();
            }
            // POST перевод
            if (Yii::$app->request->post('TransferForm') && $modelTransfer->load(Yii::$app->request->post())) {
                if (!Yii::$app->user->isGuest && $modelTransfer->validate()) {
                    $modelTransfer->run();
                    $modelTransfer->sum = '';
                }
            }
        }

        if (Yii::$app->user->isGuest) {
            $return = [
                'model' => $modelLogin,
            ];
        } else {
            $return = [
                'model' => $modelTransfer,
                'user' => Yii::$app->user->isGuest ? null : $modelLogin->getUserById(Yii::$app->user->id)
            ];
        }

        return $this->render('index', $return);
    }

    /**
     * Страница пользователей
     *
     * @return string
     */
    public function actionUsers()
    {
        $model = new User;
        return $this->render('users', [
            'model' => $model
        ]);
    }

    /**
     * Принять оплату счета
     *
     * @param $id
     */
    public function actionPay($id)
    {
        if ((int)$id) {
            Transfers::payInvoice($id);
        }
        $this->redirect('index');
    }

    /**
     * Отказаться от оплаты счета или удалить счет
     *
     * @param $id
     */
    public function actionCancel($id)
    {
        if ((int)$id) {
            Transfers::cancelInvoice($id);
        }
        $this->redirect('index');
    }

    /**
     * Выйти
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

protected/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Test / Sergeev Dmitry / ragnhild.iceland@gmail.com',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ],
    [
            'brandLabel' => 'dfg',
        'brandUrl' => 'dfg'

    ]);
    echo Nav::widget([
        'items' => [
            ['label' => 'Главная', 'url' => ['/site/index']],
            ['label' => 'Пользователи', 'url' => ['/site/users']],
        ],
        'options' => ['class' => 'navbar-nav'],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Sergeev Dmitry</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>